### ISSUE TITLE
Visualizer: search bar is not working

### ISSUE THREAD

**Issue by lilyx** [cdglabs/ohm#121]
Seems like the `/* global $ */` won't import the `$` properly, and I get `ReferenceError` for `$` when I try to active the local searching bar.

After taking a look at the whole visualizer directory, sometime we use the `document.querySelector` & `document.querySelectorAll`, and the other time we use the `$` & `$$`, which are defined locally. Is there any specific reason that we choose one over the other, except that the dollar sign could simplify the code?

If we want to choose the dollar sign all the time, maybe we should move the code that define them into `domUtil.js`? @pdubroy what do you think?

**Comment by pdubroy** [comment]
No, there's no strong reason to use one or the other. The `/* global $ &*/` just tells eslint not to complain that it's undefined -- I guess it used to be defined globally, but isn't anymore.

I considered moving it into `domUtil`,

**Comment by pdubroy** [comment]
(whoops, didn't mean to close)

I think we could move them into domUtil.

**Comment by lilyx** [comment]
I see. I could try to move them this afternoon, or you want to do it by yourself?

**Comment by pdubroy** [comment]
Feel free to do if if you have time, otherwise I can try to do it tomorrow.

Thanks for noticing and filing the bug :-)

**Comment by lilyx** [comment]
Solved by #122
