### ISSUE TITLE
Allow "named capture" so that semantics fns don't have to rely on ordering

### ISSUE THREAD

**Issue by jaredly** [cdglabs/ohm#154]
I'm imagining a syntax where `[some_name]thing` assigns the name `some_name` to whatever is captured by `thing`. If `thing` is inside of an iterator, and/or if the name `some_name` is used multiple times, then all the values of `some_name` are collected into an array
```
ApplyExp
  = [main]Exp "(" ([args]Exp ",")* ([args]Exp ",")? ")"
```

And then in the semantics, you could have
```
  {
     ApplyExp({main, args}) => ... // args is a list, because it's in an iteration, and it refers to multiple things
  }
```

**Comment by pdubroy** [comment]
Thanks for the feedback. While this kind of thing is supported by many parser generators (e.g. [PEG.js](http://pegjs.org/), and Ohm's predecessor [OMeta](http://www.tinlizzie.org/ometa/)), the fact that Ohm _doesn't_ work this way is a very deliberate design decision. The main reason is that Ohm has a strict separation between the syntax of a language (defined by the grammar) and its semantics (defined in the host language, e.g. JS), and we feel that Ohm's current design is a better fit for that philosophy.

**Comment by jaredly** [comment]
hmm I don't see this suggestion as flying in the face of that

**Comment by jaredly** [comment]
I see this as just leading to a better annotated syntax
