### ISSUE TITLE
How to say "Anything but" or except or not

### ISSUE THREAD

**Issue by jdarling** [cdglabs/ohm#161]
I have a case where I want to say allow anything except a character or character set.  Is there an easy way to do this?

Basically if it were a regular expression I could do something like [^,]+ (for repeat anything except for a comma)

**Comment by pdubroy** [comment]
Yep, the way to express that with Ohm (and PEGs in general) is with negative lookahead. For your example: `(~"," any)+`.

**Comment by jdarling** [comment]
Thanks, I was missing the any part of the equation.  Gotta find a good getting started for dummies tutorial, book, video, or something.
