### ISSUE TITLE
Handling case-insensitive keywords

### ISSUE THREAD

**Issue by pdubroy** [cdglabs/ohm#162]
As pointed out in #157, some languages (e.g. SQL and FORTRAN) have case-insensitive keywords. That is, in SQL, `sElecT` and `SELECT` are equivalent. Currently, supporting this in Ohm requires a separate rule for each letter -- e.g., `select = s e l e c t`. This is awkward an inefficient.

It would be nice to have a better solution -- either a built-in rule for case-insensitive terminals (e.g. `caseInsensitive<"select">`), or else some kind of escape hatch that would enable custom matching to be implemented as a JavaScript function for cases like this.

**Comment by joshmarinacci** [comment]
Escape hatch please!

**Comment by alexwarth** [comment]
I vote for the `caseInsensitive<>` solution because:

1. it will keep the grammar platform-independent (unlike an escape hatch), and
2. its meaning is obvious (unlike adding a special syntax for case-insensitive terminals).

**Comment by joshmarinacci** [comment]
I know, but I keep hoping. We will find more and more cases that need new syntaxes or an escape hatch.
