### ISSUE TITLE
Visualizer error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rtoal** [cdglabs/ohm#35]
For the grammar

```
Arithmetic {
  Exp     = Exp "+" number      -- plus
          | number
  number  = digit+ ("." digit+)?
}
```

and input

```
2+2
```

the visualizer script produces an error, as shown in the following screenshot

![screen shot 2015-08-09 at 11 06 52 am](https://cloud.githubusercontent.com/assets/538615/9156227/3c99e362-3e87-11e5-9115-842fd4ac3d1d.png)

The cause of the problem seems to be that in somtimes the value of `traceNode` becomes a plain `Object` and not a `Trace` object. I logged the value of `traceNode` like so:

```
  console.log(traceNode); // Added this line  
  var text = (traceNode.displayString.length > 20 && traceNode.displayString.indexOf(' ') !== -1) ?
      (traceNode.displayString.slice(0, 20) + '\u2026') : traceNode.displayString;
  var label = wrapper.appendChild(createElement('.label', text));
  label.setAttribute('title', traceNode.displayString);
```

and after processing the input `1+1` I saw

![screen shot 2015-08-09 at 11 29 01 am](https://cloud.githubusercontent.com/assets/538615/9156295/e621f1a2-3e89-11e5-95cd-528b6515c17f.png)

Somehow trace nodes are not trace nodes....

**Comment by rtoal** [comment]
A workaround is to add the following silly hack

```
  if (!('displayString' in traceNode)) {
    traceNode.displayString = '???';
  }
```

at line 294. While this avoids the problem, might the fact that a non-Trace value for `traceNode` got into the flow indicate the need for a more comprehensive fix?

**Comment by alexwarth** [comment]
Thanks for reporting this bug, Ray. The visualizer is Pat's baby -- he'll take look at this in the next day or two.

**Comment by pdubroy** [comment]
Looks like this was fixed when I reworked the visualizer this week.
