### ISSUE TITLE
postinstall script fails on windows

### ISSUE THREAD

**Issue by justinmchase** [cdglabs/ohm#42]
When on windows, simply doing:
```
npm install ohm-js
```

Fails with this error:
```
> ohm-js@0.8.6 postinstall e:\code\test\node_modules\ohm-js
> bin/dev-setup.sh; touch .install-timestamp

'bin' is not recognized as an internal or external command,
operable program or batch file.
```

I believe the postinstall script in package.json isn't valid. If I clone it locally and do ```npm link ohm-js``` instead, I can then change the path to be `bin\\dev-setup.sh` and then it works. I think it's trying to use cmd on windows instead of bash to run the script commands.

**Comment by pdubroy** [comment]
Thanks for the report. Unfortunately we don't have an easy way to test on Windows.

From what I've read (e.g. https://github.com/npm/npm/issues/6543), the best way to write cross-platform npm scripts is to use something like `"postinstall": "bash bin/postinstall.sh"`. I'll work on a fix right now.

**Comment by pdubroy** [comment]
@justinmchase, can you try installing from master (`npm install cdglabs/ohm`) and see if the postinstall script works now? If it does, I will fix up all the other npm scripts we have in the same way.

**Comment by justinmchase** [comment]
success!

**Comment by justinmchase** [comment]
This issue was fixed by 784e21f6a4dba340f32a96c377fa83550ab4ab71

**Comment by pdubroy** [comment]
I believe I fixed up the rest of the scripts in https://github.com/cdglabs/ohm/commit/9aa6162518189784b0b9daba0b7861f7c6f8c29e. Can you give some of them (e.g. `npm test` and `npm run bootstrap`) a try and open an issue if there are still problems?

Thanks.

**Comment by justinmchase** [comment]
Unfortunately I'm on iojs 3.1.0 right now so it fails due to just not building, which is known so I didn't file a bug. I will find some time to get 0.12 and try it out though. I've been upgrading a variety of projects up to iojs3+ maybe I'll take a crack at updating the ohm dependencies with native code. That could take a while though.

**Comment by pascience** [comment]
I can confirm that `npm install cdglabs/ohm-js` (at [`fe0462`](https://github.com/cdglabs/ohm/commit/fe04620831ad2c67c3d97b5525274b28c79d1452)) works on Windows 10 with Node v4.0.0.

**Comment by pdubroy** [comment]
@pascience: Thanks! Any chance you could try `npm test` and `npm run bootstrap` as well?
