### ISSUE TITLE
Proposal: Eliminate special syntax for Str

### ISSUE THREAD

**Issue by pdubroy** [cdglabs/ohm#46]
The syntax for a Str pexpr, which enters "string matching mode" for the next value in the current input stream, is currently a bit awkward:

```
G {
  start = [``ident'']
}
```

Since it's relatively uncommon to need this, and it's hard to guess what it means when you see it, what about using a parameterized rule for this instead? E.g.:

```
G {
  start = [stringMatching<ident>]
}
```

**Comment by alexwarth** [comment]
Still thinking about this, not sure whether or not I like it yet. One thing to keep in mind is that the argument(s) to a parameterized rule must have arity 1. Which means that we won't be able to just translate something like this:

```
foo = ```"a" "b"*''
```

into

```
foo = stringMatching<"a" "b"*>
```

Instead, we'll end up having to refactor the argument like this:
```
foo = stringMatching<bar>
bar = "a" b"*
```

**Comment by pdubroy** [comment]
This is obsolete now that we have the distinction between string and value rules, and the `$` syntax.
