### ISSUE TITLE
Eliminate multiple underscore arguments in tests and examples

### ISSUE THREAD

**Issue by jwmerrill** [cdglabs/ohm#54]
From the mdn page on [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode)

> strict mode requires that function parameter names be unique

The house style so far uses underscores for every argument that is not actually used in a semantic action, but this throws errors when run in strict mode. It might be better style to use `function (_1, _2, _3) {}` (or some other alternative?) instead.

**Comment by pdubroy** [comment]
Yep, you're right. I realized this when I strict-moded a bunch of our core code a while back, but I never got around to finishing the job by fixing the tests and examples.

Other than the tests and examples, do you know of anything else that needs updating?

**Comment by jwmerrill** [comment]
> Other than the tests and examples, do you know of anything else that needs updating?

No. I just checked the docs, and they don't seem to use this convention.

**Comment by pdubroy** [comment]
Ok, good to know! I thanks for filing this.

BTW, the style I've settled on is to simply give the unused arguments sensible (if somewhat terse) names. For quotes, braces, etc., I just used `open` and `close`, and for keywords I use stuff like `ifkw`, `thenkw`, `elsekw`.

**Comment by alexwarth** [comment]
Hi Jason and Pat,

I've been using Ohm in my class at UCLA, in strict mode. A style that I've
developed and seems to be working well for us is to name terms that I don't
care about (i.e., that I don't need to use) with names that start with an
underscore, but are more descriptive. E.g., for a rule like this:

  IfExpr = if Expr then Expr else Expr

(with rules if, then, and else defined to consume their respective
keywords) I would write the following semantic action:

  IfExpr: function(_if, e1, _then, e2, _else, e3) {
    ...
  }

**Comment by alexwarth** [comment]
Seems sensible to me :)

**Comment by pdubroy** [comment]
Thanks!

**Comment by pdubroy** [comment]
Re-opening as we still need to fix some of the tests (e.g. [test-ohm-syntax.js](https://github.com/cdglabs/ohm/blob/master/test/test-ohm-syntax.js#L423)).

**Comment by alexwarth** [comment]
There are still instances of the non-descriptive `_` in a bunch of the tests, e.g., in test/test-grammar.js, test/test-semantics.js.

**Comment by pdubroy** [comment]
I don't think we need to eliminate all use of `_`. I thought the point was to just to eliminate duplicate parameter names so that they code is compatible with strict mode. I don't see a problem with still using the `_` sometimes.

**Comment by alexwarth** [comment]
Oh, ok. Fine by me!
