### ISSUE TITLE
Proposal: Optional naming of terms

### ISSUE THREAD

**Issue by mroeder** [cdglabs/ohm#65]
In OMeta you had to name the rules you wanted to work with as grammar and semantic action where tightly coupled:
```
ometa Calc {
  digit    = ^digit:d                 -> d.digitValue(),
  number   = number:n digit:d         -> (n * 10 + d)
           | digit,
  addExpr  = addExpr:x '+' mulExpr:y  -> (x + y)
           | addExpr:x '-' mulExpr:y  -> (x - y)
           | mulExpr,
  mulExpr  = mulExpr:x '*' primExpr:y -> (x * y)
           | mulExpr:x '/' primExpr:y -> (x / y)
           | primExpr,
  primExpr = '(' expr:x ')'           -> x
           | number,
  expr     = addExpr
}
```
Ohm does not offer any way of doing that but so far I have seen some cases where it would have been helpful:
* automatic naming of sub-terms in operations and attributes (especially helpful for an Ohm IDE)
* CST-to-AST conversions (would reduce the necessary mapping even further)
* generic (semi-)structured editor (powered by an Ohm grammar)

Therefore my proposal is to allow (optional) naming of terms in Ohm grammars:
```
Calc {
  expr = addExpr
  addExpr = addExpr:x "+" mulExpr:y
          | addExpr:x "-" mulExpr:y
          | mulExpr
  mulExpr = mulExpr:x "*" primExpr:y
          | mulExpr:x "/" primExpr:y
          | primExpr
  primExpr = "(" expr:x ")"
           | number
  number = number:n digit:d
         | digit
}
```
Note that some optional kind of _rule naming_ is already provided by [rule descriptions](https://github.com/cdglabs/ohm/blob/master/doc/syntax-reference.md#rule-descriptions).

**Comment by alexwarth** [comment]
Hi Marko,

> Ohm does not offer any way of doing that

... but it will once tools like the grammar and semantics editor are ready. The idea is to provide an experience that's similar to OMeta when you're writing semantic actions for a grammar, and you should be able to see everything together, even though we have the increased modularity that comes from keeping grammars and semantic actions separate, etc.

I don't think that the way to get there is to add names to terms in a grammar. I feel strongly that this shouldn't be the responsibility of the author of the grammar, but rather of the person who is trying to do something with the grammar.

Also, there are some nice things that we could do in our tools that would obviate the need for this. In attribute grammars, for example, people can refer to terms using the names of the rules. E.g., if the body of a rule looks like this:

  `AddExp "+" MulExp`

then you could refer to its first and third terms as `AddExp` and `MulExp`, respectively. There are cases where these are ambiguous, but there are reasonable ways to disambiguate, e.g., by adding subscripts. I'm not sure that this is a good idea for Ohm yet, though @lilyx has been experimenting with it and it seems very nice. Regardless, I thought I'd bring it up as an example of something we could do that doesn't involve annotating the grammar.

Cheers,
Alex

**Comment by mroeder** [comment]
Thanks, Alex, for your view on this.

And, well, my argument was simply that 
> the person who is trying to do something with the grammar

has to do it over and over again as different things often need names.

I do think that the example you brought up - `AddExp "+" MulExp` - is a rather unfortunate (and, to me, a smell) and more rules should actually be like `AddExp "+" AddExp` and then naming becomes important. But this is separate topic will address some other time.

Thanks again for your opinion!

**Comment by alexwarth** [comment]
Well, that's where the subscripts that I was talking about come in. E.g., if you're writing a semantic action for

  `AddExp "+" AddExp`

you would be able to refer to the first term as `AddExp_1` and the second as `AddExp_2`. Like I said, I don't know that this is the solution that I want to go with, but it's good to know that it's there :)
