### ISSUE TITLE
Requiring ohm-js in package.json installs a pre-commit hook in my project

### ISSUE THREAD

**Issue by tonyg** [cdglabs/ohm#78]
I have a `devDependencies` line for ohm-js pointing to this github repo from my package's `package.json`. When I run `npm install .` for my package, it retrieves and installs ohm-js as expected - but then the ohm-js postinstall script runs, calling in turn dev-setup.sh, which uses `git-rev-parse` to find the `.git` directory and installs a pre-commit hook therein. Unfortunately, this leads to a pre-commit hook being added to the `.git` directory of *my* package, not ohm-js! Subsequent commits of *my* package then fail because `npm run prepublish` is being called.

**Comment by pdubroy** [comment]
Whoops! Sorry about that. Definitely not by design. I'll see if I can come up with a fix.

**Comment by pdubroy** [comment]
Hey Tony, I looked into this, and I can't actually reproduce it.

AFAICT, the `-f "$(npm prefix)/.gitignore"` test _should_ prevent the postinstall script from executing dev-setup.sh unless you are in a checkout of Ohm. Are you sure that it's getting run from postinstall? Or could it be update-env.sh that's running it?

In any case, I added another check that should ensure that we only ever install the hooks when you run `npm install` inside a checkout of the ohm-js repo. Let me know if it fixes the issue for you or not.

**Comment by tonyg** [comment]
Thanks, Patrick. The extra check means the bug doesn't manifest anymore. I'm not 100% sure, but I think the `"$(npm prefix)/.gitignore"` check might have been failing to prevent the hook installation. I have a `.gitignore` file in that location as part of my ohm-requiring project, which I guess might be irrelevant, but then also the `devDependencies` in my package.json reads `"ohm-js": "cdglabs/ohm"`, so it was checking it out from git, so perhaps the `.gitignore` was present in the nested ohm module. Anyway, the change you made seems sensible and seems to have fixed it. Thanks.
