### ISSUE TITLE
No release since November

### ISSUE THREAD

**Issue by mdebbar** [cdglabs/ohm#91]
Digging a little into Ohm's commit history, I found [this commit](https://github.com/cdglabs/ohm/commit/3ce66ea1e3dc2e1367708c75fa3b6cdc1dbcedbf). So I tried to use a leading pipe in my rules but Ohm is not accepting it. I thought I was doing something wrong. But after some time I found out that the version I'm using is 0.9.0 which was released last November and doesn't contain the "leading pipe" commit.

There has been a lot of activity since then, but there are no releases. Would it make sense to make a minor release every few changes/commits?

**Comment by mdebbar** [comment]
On a side note, I love Ohm! I'm now able to easily create parsers for anything I want :)

**Comment by pdubroy** [comment]
We are indeed overdue for a release -- thanks for the reminder. I'll do my best to get one out tomorrow.

And glad you like Ohm :-)

**Comment by pdubroy** [comment]
Just published [v0.10.0](https://www.npmjs.com/package/ohm-js). And we now have a [changelog](https://github.com/cdglabs/ohm/blob/master/CHANGELOG.md)!
