### ISSUE TITLE
How do I extend the semantics of an inherited grammar?

### ISSUE THREAD

**Issue by justinmchase** [cdglabs/ohm#99]
What I'm trying to do is to extend the es5 grammar and add some custom semantics.

First off I am able to essentially eval the es5 code like this:
```
var ohm = require('ohm-js')
var es5 = require('ohm-js/examples/ecmascript/es5')
var code = '2 + 3'
var grammar = es5.grammar
var match = grammar.match(code)
var semantics = es5.semantics
var result = semantics(match)
assert(eval(result.asES5) === 5)
```

This appears to actually work. But what I would like to do is to extend es5 and add my own semantics which then allow me to expand those semantics into javascript.

For example suppose I wrote my own grammar like this:
```
Example <: ES5 {
  example = "example"
  keyword += example
  Declaration += ExampleDeclaration
  ExampleDeclaration = "example" #(sc)
}
```

Now, I modify my original code to be more like this:
```
var ohm = require('ohm-js')
var es5 = require('ohm-js/examples/ecmascript/es5')
var code = 'example;'
var grammar = ohm.grammar(fs.readFileSync('./g.ohm'), { ES5:  es5.grammar })
var match = grammar.match(code)

var semantics = // ??

var result = semantics(match)
assert(eval(result.asES5) === 5)
```

What I would like to do, for this example, is to essentially transform the matched `ExampleDeclaration` into `2 + 3`. How can I use the es5 semantics object but modify it to do custom stuff just for my matched semantics?

**Comment by alexwarth** [comment]
Here's how you'd create a semantics for your `Example` grammar that inherits from the semantics that you created for the `ES5` grammar:

```
var semantics = grammar.extendSemantics(es5.semantics);
```

You can extend / override the semantic actions of the operations and attributes that `semantics` inherited from its super-semantics using the `extendOperation` and `extendAttribute` methods, respectively. Here's a link to the relevant part of the documentation: https://github.com/cdglabs/ohm/blob/master/doc/api-reference.md#user-content-semantics

**Comment by justinmchase** [comment]
Ok great, specifically I did this:
```
var modifiedSourceActions = {
    ExampleDeclaration: (example) => {            
        return '2 + 3'
    }
}
var semantics = grammar.extendSemantics(es5.semantics)
semantics.extendAttribute('modifiedSource', modifiedSourceActions);
```

One last question if I may!

Suppose I wanted to return an AST here instead of  calling `asES5`?

For example:
```
var ast = result.asAST
var t = transformer.match(ast) // another grammar that transforms the ast further
```

I think I want to take multiple transformation steps before reducing down to javascript.

**Comment by justinmchase** [comment]
This is pretty sweet! Inheriting from es5 lets me write tests directly in the code file being tested:

```
model Foo {
   field x
}

assert(new Foo().x)
```

Then my test code just spins through all of my source files and evals them basically. Very cool!
